---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: Display splunk app path default
  ansible.builtin.debug:
    var: _splunkapp_path 
    
- name: Find all apps
  find:
    paths: "{{ _splunkapp_path }}"
    recurse: no
    file_type: directory
  register: new_apps

- name: Determine installed apps
  set_fact:
    installed_apps: 
      - appname : "{{ (installed_apps | default([]) + [ item.path | basename ] | difference(default_apps)) | unique }}"
      - pathname: "{{ item.path }}"
  with_items: "{{ new_apps.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  

- name: Display splunk app path default
  ansible.builtin.debug:
    var: "{{ installed_apps.appname}}"
    var: "{{ installed_apps.pathname}}"
  with_items: "{{ installed_apps}}"
