---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

#- name: Display all variables/facts known for a host
#  ansible.builtin.debug:
#    var: hostvars[inventory_hostname]
#    verbosity: 4

- name: Display splunk app path default
  ansible.builtin.debug:
    var: _splunkapp_path 
    
- name: Find all apps
  find:
    paths: "{{ _splunkapp_path }}"
    recurse: no
    file_type: directory
  register: new_apps

- name: Adding apps directory  to the LIST
  set_fact:
    appsliste: "{{ appsliste | default([])  + [item.path]  }}"
  with_items: "{{ new_apps.files }}"
 
#- name: Output all apps
#  debug: 
#    var: "{{ item.path }}"
#  with_items: "{{ news_apps.files }}"
    
- name: Remove the path to only and retrieve folder name only
  set_fact:
    nameapps: "{{ item | split('/') | last }}"
  loop: "{{ appsliste }}"

#- name: Determine installed apps
#  set_fact:
#    appname : "{{ item.directory }}"
#    pathname: "{{ item.path }}"
#  with_items: "{{ new_apps.files }}"
#  loop_control:
#    label: "{{ item.path}}"
  

#- name: Display splunk app path default
#  ansible.builtin.debug:
#    var: "{{ installed_apps.appname}}"
#    var: "{{ installed_apps.pathname}}"
#  with_items: "{{ installed_apps}}"
